name: TheBestRanks
version: 1.0.2
author: thelegend
api-version: 1.13
main: com.zorbeytorunoglu.thebestranks.TBR
depend:
  - PlaceholderAPI
softdepend:
  - Vault
commands:
  rank:
    description: Main command
    aliases:
      - tbr
      - thebestranks
permissions:
  thebestranks.rank:
    description: Permission for main rank
    default: true
  thebestranks.setrank:
    description: Permission to set rank for players
    default: op
  thebestranks.check:
    description: Permission to check other players ranks
    default: true